spring.ai.google.genai.api-key=dummy
spring.ai.openai.api-key=dummy
spring.ai.mcp.client.name=analytics-agent-client
spring.ai.mcp.client.streamable-http.connections.analytics-agent-server.url=http://localhost:7070
spring.config.import=optional:file:secrets.env[.properties]
spring.profiles.active=google