spring.ai.mcp.client.name=mcp-client
spring.ai.mcp.client.streamable-http.connections.codebase-service.url=http://localhost:7070
spring.web.resources.static-locations=classpath:/${section}/static
spring.config.import=optional:file:secrets.env[.properties]
spring.profiles.active=google