server.port=8083
candidate-service.url=http://localhost:8081
job-service.url=http://localhost:8082

# Spring expects these properties when the Google / OpenAI modules are on the classpath.
# For now we use dummy values. Real keys will be loaded from secrets.env.
spring.ai.google.genai.api-key=dummy
spring.ai.openai.api-key=dummy
spring.config.import=optional:file:secrets.env[.properties]
spring.profiles.active=google
