spring.ai.mcp.client.name=mcp-playground-client
spring.config.import=optional:file:secrets.env[.properties]
spring.profiles.active=google

server.port=8080
spring.ai.mcp.client.streamable-http.connections.file-service.url=http://localhost:7070
spring.web.resources.static-locations=classpath:/${section}/static

# elicitation related
spring.threads.virtual.enabled=true
spring.ai.mcp.client.request-timeout=60s
