spring.ai.mcp.client.name=mcp-playground-client
spring.config.import=optional:file:secrets.env[.properties]
spring.profiles.active=google

server.port=8080
spring.ai.mcp.client.streamable-http.connections.city-service.url=http://localhost:7070
spring.ai.mcp.client.streamable-http.connections.flight-service.url=http://localhost:7071
spring.ai.mcp.client.streamable-http.connections.user-service.url=http://localhost:7072
spring.ai.mcp.client.streamable-http.connections.weather-service.url=http://localhost:7073
spring.web.resources.static-locations=classpath:/${section}/static